### ISSUE TITLE
Add indicator to MessageBox when trying to click main window.

### ISSUE THREAD

**Issue by KamilDev** [emako/wpfui.violeta#15]
### Is your feature request related to a problem? Please describe

When a `MessageBox` is shown, the main window can't be interacted with until the `MessageBox` is dismissed.

To better indicate this, the standard `MessageBox` will flash so the user understands they need to deal with the `MessageBox` first.

### Describe the solution you'd like

The Violeta `MessageBox` should have a similar indicator when the user tries to click on the main window while a `MessageBox` needs to be dismissed first.

Video example:

https://github.com/user-attachments/assets/339f8a19-caec-4a0d-a7bd-950239a716db

**Comment by emako** [comment]
I haven't thought about how this is achieved. Do you have any ideas?

**Comment by KamilDev** [comment]
I realized when running the built exe, it correctly flashes when trying to click on the main window. I think the bug is not related to this repo.
