### ISSUE TITLE
Should MessageBox icon be aligned to the top?

### ISSUE THREAD

**Issue by KamilDev** [emako/wpfui.violeta#17]
### Is your feature request related to a problem? Please describe

Currently the MessageBox icon is centered relative to the text. The standard MessageBox has the icon aligned to the top.

![Screenshot 2024-12-07 135034](https://github.com/user-attachments/assets/e574d043-9a7c-4c0f-aa76-18bc602f8fa6)
![Screenshot 2024-12-07 153029](https://github.com/user-attachments/assets/410883ff-564f-46ae-9085-fa510d4252b9)

### Describe the solution you'd like

Would it make more sense if the MessageBox icon were aligned to the top like the standard MessageBox?

Additionally, I feel like the title of Violeta MessageBox doesn't look distinguished/spaced enough compared to the regular message text, but it's subjective. It's also not aligned with the "X" button.
![Screenshot 2024-12-07 135034-1](https://github.com/user-attachments/assets/e3387394-09c5-4ff3-bb29-78793df9c2ee)
![Screenshot 2024-12-07 153029-1](https://github.com/user-attachments/assets/302b0a4c-3de3-4216-9ef0-be89c74b0288)

**Comment by KamilDev** [comment]
I've made the following PR with improvements: https://github.com/emako/wpfui.violeta/pull/18

**Comment by emako** [comment]
Completed
