### ISSUE TITLE
[Feature request] approach to File Explorer

### ISSUE THREAD

**Issue by emako** [emako/wpfui.violeta#3]
### Is your feature request related to a problem? Please describe

/

### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/6000de59-3084-4ca4-bd2c-24cfe9b15111)

**Comment by emako** [comment]
> How to get file icon from syswin32 https://github.com/emako/QuickLook.Plugin.TorrentViewer/blob/master/QuickLook.Plugin/QuickLook.Plugin.TorrentViewer/IconManager.cs

**Comment by huiyadanli** [comment]
What? This is too complicated
